[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m flask run --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_APP = "src.main:app"
FLASK_ENV = "production"

